To do list - React JS
RitobrotoMukherjee/react-to-do pull request #1
Opened 2022-07-05 05:04 UTC by RitobrotoMukherjee

## Developed To Do List
- Used `CRA`
- Used `class component` and `functional component` both for practice
- Did basic styling for the wireframe
- Used `CSS flexbox`
- Saved data in `localStorage`
- Implemented `React Router` to show only `about` page
- Implemented **menu** as **sidebar**
- Followed `Parent - Child Layout` based architecture
- Followed `DRY`, `KISS` and `YAGNI`

2022-07-05 13:10 UTC, Chrissiku requested changes
Hi @RitobrotoMukherjee  , 

## Status : Request Changes  

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Higlights 👍 
- No linters errors ✔️ 
- Use of gitflow ✔️ 
- Use of github workflow ✔️ 
-  No linters errors ✔️ 
-  Use of React components and Hooks✔️

## Suggested changes ♻️ 

- [ ] Using the enter key to add new to-dos works correctly but it would be better to also add a button, as shown on the image bellow,  for a better user experience and accessibility
![changes](https://user-images.githubusercontent.com/101924220/177334214-fbaa68a1-4f66-475b-a244-a61613dc026d.PNG)


## _Check Also the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-05 13:10 UTC, Chrissiku commented on src/index.js
> +);
- [x] Kindly ensure you implement the routing as listed in the project instructions. You can read. You can use the [ given link](https://ibaslogic.com/routing-with-react-router/), which will help you implement that

### Instruction given instruction
![routing](https://user-images.githubusercontent.com/101924220/177331939-c473b652-cdcf-474c-a381-0ec2ec7216f4.PNG)

2022-07-05 13:33 UTC, RitobrotoMukherjee commented
Hi @Chrissiku,

Thanks for the review and the suggestions. Will implement ASAP.

2022-07-08 08:14 UTC, Kimutai01 approved these changes
Hi @RitobrotoMukherjee  :wave: 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :tada: 

Cheers and Happy coding! :clap: :clap: 
![unnamed](https://user-images.githubusercontent.com/86611927/177948153-3e3357fd-8de2-487a-8a1b-8e829198d8cb.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-07-08 08:33 UTC, RitobrotoMukherjee commented
Hi @Kimutai01,

Thanks for approving my project. ⏩

2022-07-08 08:44 UTC, merged